Line width for drawing  (#706)
* static polygon on finish drawed

* line drawing upon finishing with fixed width

* Line box added

* pointer z-index patch (#703)

* line drawing box and drawing manager updates

* undefined reference to overlay

* Transition

* fixing bug on back button click

* adding styles to buffer zone on drawing

* fixing merge conflict typo

Co-authored-by: Jimmy Rowland <jimmyrowland@protonmail.com>
Co-authored-by: Kaavya Lakshmanan <kaavya.laks@gmail.com>